/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 phone.glb --types --transform
Files: phone.glb [1.97MB] > E:\projects\parapluie.app\public\models\phone-transformed.glb [140.27KB] (93%)
*/

import * as THREE from "three";
import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Circle_camera_base_0: THREE.Mesh;
    Circle_glass_0: THREE.Mesh;
    Plane_antenna_0: THREE.Mesh;
    Plane_screen_0: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    screen: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export const Phone = forwardRef<Group, JSX.IntrinsicElements["group"]>(
  (props, ref) => {
    const { nodes, materials } = useGLTF(
      "/models/phone-transformed.glb"
    ) as GLTFResult;
    return (
      <group ref={ref} {...props} dispose={null}>
        <mesh
          geometry={nodes.Circle_camera_base_0.geometry}
          material={materials.PaletteMaterial001}
          position={[0.024, 0.092, -0.007]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.Circle_glass_0.geometry}
          material={materials.glass}
          position={[0.024, 0.092, -0.007]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.Plane_antenna_0.geometry}
          material={materials.PaletteMaterial002}
          scale={0.063}
        />
        <mesh
          geometry={nodes.Plane_screen_0.geometry}
          material={materials.screen}
          scale={0.063}
        />
      </group>
    );
  }
);

Phone.displayName = "Phone";

useGLTF.preload("/models/phone-transformed.glb");
