/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 umbrella.glb --types --transform
Files: umbrella.glb [6.03MB] > E:\projects\parapluie.app\public\models\umbrella-transformed.glb [205.28KB] (97%)
*/

import * as THREE from "three";
import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group } from "three";

type GLTFResult = GLTF & {
  nodes: {
    umbrella: THREE.Mesh;
  };
  materials: {
    ["umbrella-material"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export const Umbrella = forwardRef<Group, JSX.IntrinsicElements["group"]>(
  (props, ref) => {
    const { nodes, materials } = useGLTF(
      "/models/umbrella-transformed.glb"
    ) as GLTFResult;
    return (
      <group ref={ref} {...props} dispose={null}>
        <mesh
          geometry={nodes.umbrella.geometry}
          material={materials["umbrella-material"]}
        />
      </group>
    );
  }
);

Umbrella.displayName = "Umbrella";

useGLTF.preload("/models/umbrella-transformed.glb");
