/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 walter.glb --types --transform
Files: walter.glb [4.87MB] > E:\projects\parapluie.app\public\models\walter-transformed.glb [149.33KB] (97%)
*/

import * as THREE from "three";
import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group } from "three";

type GLTFResult = GLTF & {
  nodes: {
    walter: THREE.Mesh;
  };
  materials: {
    ["walter-material"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export const Walter = forwardRef<Group, JSX.IntrinsicElements["group"]>(
  (props, ref) => {
    const { nodes, materials } = useGLTF(
      "/models/walter-transformed.glb"
    ) as GLTFResult;
    return (
      <group ref={ref} {...props} dispose={null}>
        <mesh
          geometry={nodes.walter.geometry}
          material={materials["walter-material"]}
        />
      </group>
    );
  }
);

Walter.displayName = "Walter";

useGLTF.preload("/models/walter-transformed.glb");
