/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pixel10.glb --types --transform
Files: pixel10.glb [6.41MB] > E:\projects\parapluie.app\public\pixel10-transformed.glb [271.55KB] (96%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    walter: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
  };
  materials: {
    model: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Pixel10(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/pixel10-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.walter.geometry}
        material={materials.model}
        position={[-6.948, 1.288, 5.809]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["Material.003"]}
        position={[-0.482, -0.591, 1.737]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[2.39, 1.783, 1.119]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.004"]}
        position={[-0.482, -0.591, 1.737]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[2.39, 1.783, 1.119]}
      />
    </group>
  );
}

useGLTF.preload("/pixel10-transformed.glb");
