/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pixel.glb --types --transform
Files: pixel.glb [187.12KB] > E:\projects\parapluie.app\public\pixel-transformed.glb [27.1KB] (86%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Pixel10(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/pixel-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["Material.003"]}
        position={[-0.482, -0.591, 1.737]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[2.39, 1.783, 1.119]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.004"]}
        position={[-0.482, -0.591, 1.737]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={[2.39, 1.783, 1.119]}
      />
    </group>
  );
}

useGLTF.preload("/pixel-transformed.glb");
