/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 umbrella.glb --types --transform
Files: umbrella.glb [6.03MB] > E:\projects\parapluie.app\public\umbrella-transformed.glb [205.26KB] (97%)
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh;
  };
  materials: {
    model: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type UmbrellaProps = {
  scroll?: number;
} & JSX.IntrinsicElements["group"];

export function Umbrella({ scroll = 0, ...props }: UmbrellaProps) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/umbrella-transformed.glb",
  ) as GLTFResult;

  // Use this hook if your GLTF has embedded animations
  const { actions, names } = useAnimations(animations, group);

  // Play embedded animations (if they exist)
  useEffect(() => {
    if (names.length > 0) {
      // Play the first animation
      actions[names[0]]?.play();
    }
  }, [actions, names]);

  // Custom animation with useFrame
  useFrame((state) => {
    if (group.current) {
      // Rotate the umbrella
      group.current.rotation.y += 0.01;

      // Bob up and down with sine wave
      group.current.position.y = Math.sin(state.clock.elapsedTime) * 0.2;

      // Scale based on scroll
      const scale = 1 + scroll * 0.5;
      group.current.scale.set(scale, scale, scale);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  );
}

useGLTF.preload("/umbrella-transformed.glb");
