/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 walter.gltf --types
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX } from "react";
import { Float } from "@react-three/drei";

type GLTFResult = GLTF & {
  nodes: {
    WalterBody: THREE.Mesh;
    Umbrella: THREE.Mesh;
    model: THREE.Mesh;
  };
  materials: {
    WalterMaterial: THREE.MeshStandardMaterial;
    UmbrellaMaterial: THREE.MeshStandardMaterial;
    model: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type WalterProps = {
  scroll?: number;
  position?: [number, number, number];
} & JSX.IntrinsicElements["group"];

export function Walter({ scroll = 0, ...props }: WalterProps) {
  const { nodes, materials } = useGLTF("/walter-transformed.glb") as GLTFResult;
  const umbrellaRef = useRef<THREE.Mesh>(null);
  const walterRef = useRef<THREE.Mesh>(null);

  useFrame(() => {
    if (umbrellaRef.current) {
      umbrellaRef.current.rotation.y += 0.02;

      const openAmount = 1 + scroll * 0.5;
      umbrellaRef.current.scale.set(openAmount, 1, openAmount);
    }
  });

  return (
    <group {...props} dispose={null}>
      <Float speed={1.5} rotationIntensity={0.5} />
      <mesh geometry={nodes.model.geometry} material={materials.model} />
      <mesh
        ref={umbrellaRef}
        geometry={nodes.model.geometry}
        material={materials.model}
        position={[0, 1, 0]}
      />
    </group>
  );
}

useGLTF.preload("/walter-transformed.glb");
