/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 walter-t-pose.glb --types --transform
Files: walter-t-pose.glb [4.87MB] > E:\projects\parapluie.app\public\walter-t-pose-transformed.glb [149.3KB] (97%)
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh;
  };
  materials: {
    model: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type WalterTPoseProps = {
  scroll?: number;
} & JSX.IntrinsicElements["group"];

export function WalterTPose({ scroll = 0, ...props }: WalterTPoseProps) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/walter-t-pose-transformed.glb",
  ) as GLTFResult;

  // Use this hook if your GLTF has embedded animations
  const { actions, names } = useAnimations(animations, group);

  // Play embedded animations (if they exist)
  useEffect(() => {
    if (names.length > 0) {
      // Play all animations or select specific ones
      actions[names[0]]?.play();
    }
  }, [actions, names]);

  // Custom scroll-based animation
  useFrame((state) => {
    if (group.current) {
      // Move Walter based on scroll
      group.current.position.x = -2 + scroll * 3; // Move from left to right
      group.current.position.y = scroll * -2; // Move down as you scroll

      // Rotate based on scroll
      group.current.rotation.y = scroll * Math.PI * 2; // Full rotation
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  );
}

useGLTF.preload("/walter-t-pose-transformed.glb");
